// src/utils/pdfExport.js - Utility for exporting data to PDF format

import { jsPDF } from 'jspdf';

/**
 * Generate PDF report for entity data
 * @param {Array} data - Data to export
 * @param {Object} config - Configuration object
 * @param {string} config.title - Report title
 * @param {string} config.entityType - Type of entity (trucks, drivers, etc.)
 * @param {string} config.timeframe - Current timeframe
 * @param {Array} config.columns - Column definitions for the table
 * @param {Object} config.summary - Summary statistics
 */
export const generatePDFReport = (data, config) => {
  const { title, entityType, timeframe, columns, summary } = config;
  
  // Create new PDF document
  const doc = new jsPDF();
  
  // Set up colors
  const primaryColor = [59, 130, 246]; // Blue
  const secondaryColor = [107, 114, 128]; // Gray
  const successColor = [34, 197, 94]; // Green
  
  // Add header
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, 210, 30, 'F');
  
  // Add title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 20, 20);
  
  // Add subtitle with timeframe
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Timeframe: ${timeframe}`, 20, 28);
  
  // Add generation date
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  doc.text(`Generated: ${currentDate}`, 20, 35);
  
  // Add summary section
  if (summary) {
    doc.setFillColor(248, 250, 252);
    doc.rect(20, 45, 170, 25, 'F');
    
    doc.setTextColor(31, 41, 55);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Summary', 25, 55);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(107, 114, 128);
    
    let yPos = 62;
    Object.entries(summary).forEach(([key, value]) => {
      const label = key.charAt(0).toUpperCase() + key.slice(1).replace(/([A-Z])/g, ' $1');
      doc.text(`${label}: ${value}`, 25, yPos);
      yPos += 5;
    });
  }
  
  // Prepare table data
  const tableData = data.map(item => {
    return columns.map(col => {
      const value = item[col.key];
      if (value === null || value === undefined) return '';
      
      // Format specific data types
      if (col.type === 'date' && value) {
        return new Date(value).toLocaleDateString();
      }
      if (col.type === 'currency' && value) {
        return new Intl.NumberFormat('en-PH', {
          style: 'currency',
          currency: 'PHP'
        }).format(value);
      }
      if (col.type === 'status' && value) {
        return value.charAt(0).toUpperCase() + value.slice(1);
      }
      
      return String(value);
    });
  });
  
  // Create table manually
  let yPos = summary ? 75 : 50;
  const rowHeight = 8;
  const colWidths = [35, 30, 35, 30, 25];
  let xPos = 20;
  
  // Draw header
  doc.setFillColor(...primaryColor);
  doc.rect(xPos, yPos, colWidths.reduce((a, b) => a + b, 0), rowHeight, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  
  columns.forEach((col, index) => {
    doc.text(col.label, xPos + 2, yPos + 5);
    xPos += colWidths[index];
  });
  
  yPos += rowHeight;
  
  // Draw data rows
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');
  
  tableData.forEach((row, rowIndex) => {
    if (yPos > 280) {
      doc.addPage();
      yPos = 20;
    }
    
    // Alternate row colors
    if (rowIndex % 2 === 0) {
      doc.setFillColor(249, 250, 251);
      doc.rect(20, yPos - 2, colWidths.reduce((a, b) => a + b, 0), rowHeight, 'F');
    }
    
    xPos = 20;
    row.forEach((cell, colIndex) => {
      // Truncate long text
      const cellText = String(cell).length > 20 ? String(cell).substring(0, 17) + '...' : String(cell);
      doc.text(cellText, xPos + 2, yPos + 5);
      xPos += colWidths[colIndex];
    });
    
    yPos += rowHeight;
  });
  
  // Add footer to all pages
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(107, 114, 128);
    doc.text(`Page ${i} of ${pageCount}`, 20, 285);
    doc.text(`Generated by Trucking Management System`, 120, 285);
  }
  
  return doc;
};

/**
 * Download PDF file
 * @param {jsPDF} doc - PDF document object
 * @param {string} filename - Name of the file to download
 */
export const downloadPDF = (doc, filename) => {
  doc.save(filename);
};

/**
 * Export data to PDF with proper formatting
 * @param {Array} data - Data to export
 * @param {Object} config - Configuration object
 */
export const exportToPDF = (data, config) => {
  const doc = generatePDFReport(data, config);
  const filename = generatePDFFilename(config.entityType, config.timeframe);
  downloadPDF(doc, filename);
};

/**
 * Generate filename for PDF export
 * @param {string} entityType - Type of entity
 * @param {string} timeframe - Current timeframe
 * @returns {string} Formatted filename
 */
export const generatePDFFilename = (entityType, timeframe) => {
  const date = new Date().toISOString().split('T')[0];
  const timeframeStr = timeframe.replace(/\s+/g, '_');
  return `${entityType}_Report_${timeframeStr}_${date}.pdf`;
};

/**
 * Get current date string for filename
 * @returns {string} Current date in YYYY-MM-DD format
 */
export const getCurrentDateString = () => {
  return new Date().toISOString().split('T')[0];
};